# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.WORKFLOWS_TOKEN}}
updates:
  - package-ecosystem: "npm" # See documentation for possible values 
    directory: "/" # Location of package manifests
    registries: 
      - npm-github
    target-branch: "dev"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*" #All the dependency it gonna ignore for major update
        update-types: [ "version-update:semver-major" ]