version: '3.7'

services:
  mocked-api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - "./:/usr/src/app/"

  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local