name: Test CI

on:
  pull_request:
    branches: [ "main", "v.0.13.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependecies with Yarn
      run: |
        yarn install

    - name: Run tests with Jest
      run: |
        yarn test